[package]
name = "fmodel-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.49"

[dev-dependencies]
derive_more = "0.99.17"
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
