/*
 * Axon Synapse API
 *
 * API for Axon Synapse http services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


use reqwest;

use crate::apis::ResponseContent;
use super::{Error, configuration};


/// struct for typed errors of method [`send_command`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SendCommandError {
    Status400(crate::models::Error),
    Status404(crate::models::Error),
    Status500(crate::models::Error),
    Status502(crate::models::Error),
    Status504(crate::models::Error),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`send_command_message`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SendCommandMessageError {
    Status400(crate::models::Error),
    Status404(crate::models::Error),
    Status500(crate::models::Error),
    Status502(crate::models::Error),
    Status504(crate::models::Error),
    UnknownValue(serde_json::Value),
}


pub async fn send_command(configuration: &configuration::Configuration, context: &str, command_name: &str, axon_iq_payload_type: Option<&str>, axon_iq_payload_revision: Option<&str>, axon_iq_priority: Option<i32>, axon_iq_routing_key: Option<&str>, body: Option<std::path::PathBuf>) -> Result<std::path::PathBuf, Error<SendCommandError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/v1/contexts/{context}/commands/{commandName}", local_var_configuration.base_path, context=crate::apis::urlencode(context), commandName=crate::apis::urlencode(command_name));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(local_var_param_value) = axon_iq_payload_type {
        local_var_req_builder = local_var_req_builder.header("AxonIQ-PayloadType", local_var_param_value.to_string());
    }
    if let Some(local_var_param_value) = axon_iq_payload_revision {
        local_var_req_builder = local_var_req_builder.header("AxonIQ-PayloadRevision", local_var_param_value.to_string());
    }
    if let Some(local_var_param_value) = axon_iq_priority {
        local_var_req_builder = local_var_req_builder.header("AxonIQ-Priority", local_var_param_value.to_string());
    }
    if let Some(local_var_param_value) = axon_iq_routing_key {
        local_var_req_builder = local_var_req_builder.header("AxonIQ-RoutingKey", local_var_param_value.to_string());
    }
    if let Some(ref local_var_apikey) = local_var_configuration.api_key {
        let local_var_key = local_var_apikey.key.clone();
        let local_var_value = match local_var_apikey.prefix {
            Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
            None => local_var_key,
        };
        local_var_req_builder = local_var_req_builder.header("X-API-KEY", local_var_value);
    };
    local_var_req_builder = local_var_req_builder.json(&body);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<SendCommandError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

pub async fn send_command_message(configuration: &configuration::Configuration, context: &str, command_message: Option<crate::models::CommandMessage>) -> Result<crate::models::CommandResponseMessage, Error<SendCommandMessageError>> {
    let local_var_configuration = configuration;

    let local_var_client = &local_var_configuration.client;

    let local_var_uri_str = format!("{}/v1/contexts/{context}/commands", local_var_configuration.base_path, context=crate::apis::urlencode(context));
    let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

    if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
        local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
    }
    if let Some(ref local_var_apikey) = local_var_configuration.api_key {
        let local_var_key = local_var_apikey.key.clone();
        let local_var_value = match local_var_apikey.prefix {
            Some(ref local_var_prefix) => format!("{} {}", local_var_prefix, local_var_key),
            None => local_var_key,
        };
        local_var_req_builder = local_var_req_builder.header("X-API-KEY", local_var_value);
    };
    local_var_req_builder = local_var_req_builder.json(&command_message);

    let local_var_req = local_var_req_builder.build()?;
    let local_var_resp = local_var_client.execute(local_var_req).await?;

    let local_var_status = local_var_resp.status();
    let local_var_content = local_var_resp.text().await?;

    if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
        serde_json::from_str(&local_var_content).map_err(Error::from)
    } else {
        let local_var_entity: Option<SendCommandMessageError> = serde_json::from_str(&local_var_content).ok();
        let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
        Err(Error::ResponseError(local_var_error))
    }
}

