/*
 * Axon Synapse API
 *
 * API for Axon Synapse http services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ClientAuthenticationTokenPrototype : Authentication used by synapse to call the registered handler



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClientAuthenticationTokenPrototype {
    /// Name to recognize this stored authentication
    #[serde(rename = "name")]
    pub name: String,
    /// secret token used in authentication
    #[serde(rename = "token")]
    pub token: String,
}

impl ClientAuthenticationTokenPrototype {
    /// Authentication used by synapse to call the registered handler
    pub fn new(name: String, token: String) -> ClientAuthenticationTokenPrototype {
        ClientAuthenticationTokenPrototype {
            name,
            token,
        }
    }
}


