/*
 * Axon Synapse API
 *
 * API for Axon Synapse http services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EndpointOption : additional property for a handler



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EndpointOption {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
}

impl EndpointOption {
    /// additional property for a handler
    pub fn new() -> EndpointOption {
        EndpointOption {
            key: None,
            value: None,
        }
    }
}


