/*
 * Axon Synapse API
 *
 * API for Axon Synapse http services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// EventHandlerRegistration : Event handler registration



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct EventHandlerRegistration {
    #[serde(rename = "names")]
    pub names: Vec<String>,
    /// Message-handling client application endpoint
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    /// Type of client application endpoint - `http-raw` endpoint type is served with single raw event payload - `http-message` endpoint type is served with single event message - `http-list-of-messages` endpoint type is served with batched event messages 
    #[serde(rename = "endpointType", skip_serializing_if = "Option::is_none")]
    pub endpoint_type: Option<String>,
    #[serde(rename = "endpointOptions", skip_serializing_if = "Option::is_none")]
    pub endpoint_options: Option<Vec<crate::models::EndpointOption>>,
    /// Unique client application identifier
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Client application name
    #[serde(rename = "componentName", skip_serializing_if = "Option::is_none")]
    pub component_name: Option<String>,
    /// Number of events to send 
    #[serde(rename = "batchSize", skip_serializing_if = "Option::is_none")]
    pub batch_size: Option<i32>,
    /// Position in the event stream from which the event handler receives event - `0` indicates the oldest (very first) position (tail of the stream) - `-1` indicates the latest (newest) position (head of the stream) 
    #[serde(rename = "start", skip_serializing_if = "Option::is_none")]
    pub start: Option<i64>,
    /// Is this command handler enabled?
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Context name
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    /// Id of the stored authentication used by synapse to call the registered handler
    #[serde(rename = "clientAuthenticationId", skip_serializing_if = "Option::is_none")]
    pub client_authentication_id: Option<String>,
    /// Id of the stored authentication used by synapse to contact axon server for this registration
    #[serde(rename = "serverAuthenticationId", skip_serializing_if = "Option::is_none")]
    pub server_authentication_id: Option<String>,
    /// The last error occuring with this handler
    #[serde(rename = "lastError", skip_serializing_if = "Option::is_none")]
    pub last_error: Option<String>,
}

impl EventHandlerRegistration {
    /// Event handler registration
    pub fn new(names: Vec<String>, endpoint: String) -> EventHandlerRegistration {
        EventHandlerRegistration {
            names,
            endpoint,
            endpoint_type: None,
            endpoint_options: None,
            client_id: None,
            component_name: None,
            batch_size: None,
            start: None,
            enabled: None,
            context: None,
            client_authentication_id: None,
            server_authentication_id: None,
            last_error: None,
        }
    }
}


