/*
 * Axon Synapse API
 *
 * API for Axon Synapse http services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListOfServerAuthentication : List of Server Authentication objects



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOfServerAuthentication {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::ServerAuthentication>>,
}

impl ListOfServerAuthentication {
    /// List of Server Authentication objects
    pub fn new() -> ListOfServerAuthentication {
        ListOfServerAuthentication {
            items: None,
        }
    }
}


