/*
 * Axon Synapse API
 *
 * API for Axon Synapse http services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListOfClientAuthentication : List of Client Authentication objects



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOfClientAuthentication {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::ClientAuthentication>>,
}

impl ListOfClientAuthentication {
    /// List of Client Authentication objects
    pub fn new() -> ListOfClientAuthentication {
        ListOfClientAuthentication {
            items: None,
        }
    }
}


