/*
 * Axon Synapse API
 *
 * API for Axon Synapse http services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ListOfEventMessages : List of event messages



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListOfEventMessages {
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<crate::models::EventMessage>>,
}

impl ListOfEventMessages {
    /// List of event messages
    pub fn new() -> ListOfEventMessages {
        ListOfEventMessages {
            items: None,
        }
    }
}


