/*
 * Axon Synapse API
 *
 * API for Axon Synapse http services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// QueryHandlerRegistration : Query handler registration



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct QueryHandlerRegistration {
    #[serde(rename = "names")]
    pub names: Vec<String>,
    /// Message-handling client application endpoint
    #[serde(rename = "endpoint")]
    pub endpoint: String,
    /// Type of client application endpoint - `http-raw` endpoint type is served with single raw query payload - `http-message` endpoint type is served with single query message 
    #[serde(rename = "endpointType", skip_serializing_if = "Option::is_none")]
    pub endpoint_type: Option<String>,
    #[serde(rename = "endpointOptions", skip_serializing_if = "Option::is_none")]
    pub endpoint_options: Option<Vec<crate::models::EndpointOption>>,
    /// Unique client application identifier
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    /// Client application name
    #[serde(rename = "componentName", skip_serializing_if = "Option::is_none")]
    pub component_name: Option<String>,
    /// Is this command handler enabled?
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    /// Context name
    #[serde(rename = "context", skip_serializing_if = "Option::is_none")]
    pub context: Option<String>,
    /// Id of the stored authentication used by synapse to call the registered handler
    #[serde(rename = "clientAuthenticationId", skip_serializing_if = "Option::is_none")]
    pub client_authentication_id: Option<String>,
    /// Id of the stored authentication used by synapse to contact axon server for this registration
    #[serde(rename = "serverAuthenticationId", skip_serializing_if = "Option::is_none")]
    pub server_authentication_id: Option<String>,
    /// The last error occuring with this handler
    #[serde(rename = "lastError", skip_serializing_if = "Option::is_none")]
    pub last_error: Option<String>,
}

impl QueryHandlerRegistration {
    /// Query handler registration
    pub fn new(names: Vec<String>, endpoint: String) -> QueryHandlerRegistration {
        QueryHandlerRegistration {
            names,
            endpoint,
            endpoint_type: None,
            endpoint_options: None,
            client_id: None,
            component_name: None,
            enabled: None,
            context: None,
            client_authentication_id: None,
            server_authentication_id: None,
            last_error: None,
        }
    }
}


