/*
 * Axon Synapse API
 *
 * API for Axon Synapse http services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ServerAuthentication : Authentication used by synapse to contact axon server on behalf of another application



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerAuthentication {
    /// Name to recognize this stored authentication
    #[serde(rename = "name")]
    pub name: String,
    /// Id of the stored authentication used by synapse to contact axon server for this registration
    #[serde(rename = "id")]
    pub id: String,
}

impl ServerAuthentication {
    /// Authentication used by synapse to contact axon server on behalf of another application
    pub fn new(name: String, id: String) -> ServerAuthentication {
        ServerAuthentication {
            name,
            id,
        }
    }
}


