/*
 * Axon Synapse API
 *
 * API for Axon Synapse http services
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ServerAuthenticationTokenPrototype : Authentication used by synapse to contact axon server on behalf of another application



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServerAuthenticationTokenPrototype {
    /// Name to recognize this stored authentication
    #[serde(rename = "name")]
    pub name: String,
    /// secret token used in authentication
    #[serde(rename = "token")]
    pub token: String,
}

impl ServerAuthenticationTokenPrototype {
    /// Authentication used by synapse to contact axon server on behalf of another application
    pub fn new(name: String, token: String) -> ServerAuthenticationTokenPrototype {
        ServerAuthenticationTokenPrototype {
            name,
            token,
        }
    }
}


