version: '3.8'
services:
  axoniq-synapse:
    platform: linux/arm64
    hostname: axoniq-synapse
    build:
      context: ./synapse
      dockerfile: Dockerfile
    environment:
      - synapse.serverList=axonserver-enterprise-1:8124
    ports:
      - '8080:8080'
    networks:
      - axon-net
  axonserver-enterprise-1:
    platform: linux/arm64
    image: axoniq/axonserver-enterprise:2023.0.1-jdk-17-dev
    hostname: axonserver-enterprise-1
    environment:
      - SERVER_PORT=8024
      - AXONIQ_AXONSERVER_PORT=8124
      - AXONIQ_AXONSERVER_METRICS_GRPC_ENABLED=true
      - AXONIQ_AXONSERVER_METRICS_GRPC_PROMETHEUS-ENABLED=true
    volumes:
      - axonserver-enterprise-1-log:/axonserver/log
      - axonserver-enterprise-1-events:/axonserver/events
      - axonserver-enterprise-1-data:/axonserver/data
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    networks:
      - axon-net

volumes:
  axonserver-enterprise-1-log:
  axonserver-enterprise-1-events:
  axonserver-enterprise-1-data:

networks:
  axon-net:

