POST http://localhost:8000/commands
Content-Type: application/json

{
  "name": "IssueGiftCard",
  "routingKey": "1",
  "payload": {
    "amount": 3000,
    "id": "1",
    "type": "Issue"
  },
  "payloadType": "IssueGiftCard"
}

###

POST http://localhost:8000/gift_card_commands
Content-Type: application/json

{
  "amount": 2000,
  "id": "1234",
  "type": "Issue"
}